In [3]:
import pandas as pd

df_raw = pd.read_csv("../data/raw/haunted_places.tab", sep = "\t") 
df_cleaned = pd.read_csv("../data/processed/haunted_places_cleaned.tab", sep = "\t")
entry_no =  9152

## Entire Entry

In [4]:
df_raw[df_raw.index == entry_no]

,city,country,description,location,state,state_abbrev,longitude,latitude,city_longitude,city_latitude
9152,Laredo,United States,There's a rest room that has been closed for y...,Alma pierce elementary,Texas,TX,-99.489931,27.535793,-99.480324,27.530567

## Description Printout

In [121]:
df_raw['description'][entry_no]

"It is said that the area was and is still used by the KKK. There is a bridge,it is said people were killed under this bridge. If you put your keys on the bridge for 5 mins,Your car will not start. The road is very bad tho. Its is really hilly and also has no winter maintance. Be alarmed we recentaly walkedup a hill with what looks like a path on it. It is said a the top is the meeting ground. We were walking up the path when i turned the light on the camera on, there in the woods we then seen a white figure. We did not stick around long enough to investigate it. - October 2004 correction: The family that died under the bridge were early setlers in the area from the late 1700's (when the county began to be settled) and some have reported the mother frantically looking for her childen in the underbrush. You can hear the rustling of the bushes and a plaintive call in the distance. Some have reported that she carries a glowing taper or lantern."

### Look for a word

In [28]:
# Interesting keywords: {"indian: 258", "john: 69", "president": 28}
keyword = 'pilot'
df_raw[df_raw['description'].
        str.lower()
        .str.split()
        .explode()
        .str.strip()
        .eq(keyword)
        .groupby(level=0).any()
]

# df_cleaned[df_cleaned['description'].
#        str.lower()
#        .str.split()
#        .explode()
#        .str.strip()
#        .eq(keyword)
#        .groupby(level=0).any()
# ]

,city,country,description,location,state,state_abbrev,longitude,latitude,city_longitude,city_latitude
1471,Easton,United States,A small passenger plane crashed into the pond ...,Stonehill College,Massachusetts,MA,-71.080628,42.059015,-71.128659,42.024544
3897,Cincinnati,United States,"Cincinnati Museum Center - In the early 1990s,...",Hamilton County,Ohio,OH,-84.512020,39.103118,-84.512020,39.103118
3961,Dayton,United States,Little Vietnamese boy who walks the museum at ...,Air Force Museum,Ohio,OH,-84.109382,39.780796,-84.191607,39.758948
4456,Tabernacle,United States,A long Road in the pines said to be the living...,Caranza Road,New Jersey,NJ,-74.708632,39.837759,-74.710705,39.843385
5293,Olathe,United States,This location is the former Olathe Naval Air S...,New Century Air Center,Kansas,KS,-94.891483,38.831083,-94.819129,38.881396
7316,South Bend,United States,Some flight attendants and pilots who stay at ...,Holiday Inn City Center,Indiana,IN,-86.249530,41.716614,-86.251990,41.676355
7651,Exeter,United States,There is an old pilot who said there used to b...,Lindenshire Trailer Park,New Hampshire,NH,-70.965523,42.967331,-70.947755,42.981429
7787,Fallon,United States,There are several places in the base claim to ...,NAS Fallon,Nevada,NV,-118.726202,39.402996,-118.777041,39.474869
9405,Smith County,United States,There was a small private plane crashed betwee...,Billy Hollow RD,Tennessee,TN,-85.845315,36.383281,-85.971322,36.238847
9656,Polk,United States,Fantasy of Flight Aircraft Museum - Owner coll...,Polk City,Florida,FL,-81.823968,28.182515,-81.691156,27.861735
10117,Ellsworth,United States,Missile site - The spirit of a pilot killed in...,Air forse Base,South Dakota,SD,-103.090166,44.153815,-103.090166,44.153815