Alchohol Abuse and Haunted Dataset Join

Description:

This notebook joins the alchohol abuse dataset with the cleaned haunted places dataset. It adds 2 features ("Total Deaths" and "% Under 21") to the haunted places dataset based on the "state" column using an inner join.

In [8]:
import pandas as pd

## Copy this code into your preamble. 

# Output Df
outfile = "../data/processed/haunted_places_features_added.tab"

# Reading CSV
haunted_places_df = pd.read_csv("../data/processed/haunted_places_cleaned.tab", sep = "\t")

# Feature Names
feature_names = ["Total_Deaths", "Percent_Under_21"]


# Get the 2 datasets (alchohol abuse and haunted places) 
alcohol_abuse_path = "../data/joined_datasets/alchohol_abuse_dataset.csv"
#haunted_places_path = "../data/processed/haunted_places_cleaned.tab"

# Load datasets
alcohol_abuse_df = pd.read_csv(alcohol_abuse_path)
#haunted_places_df = pd.read_csv(haunted_places_path, sep="\t")  # Tab-separated file

# Standardize column names for merging
alcohol_abuse_df.rename(columns={"State": "State", "Total Deaths": "Total_Deaths", "% Under 21" : "Percent_Under_21"}, inplace=True)

# Merge datasets on 'state' column
merged_df = pd.merge(haunted_places_df, alcohol_abuse_df, on="State", how="inner")

# Save dataset
#merged_df.to_csv("../data/processed/merged_haunted_alcohol.csv", index=False)

## Save CSV ##
print("Saving to CSV...")

# Read Feature added dataframe
out_df = pd.read_csv(f"{outfile}", sep = "\t")


# Check if feature exists
for feature in feature_names:
    # Check if the feature exists in out_df columns
    if feature in out_df.columns:
        # Update values from merged_df (not haunted_places_df)
        out_df[feature].update(merged_df[feature].values)
    else:
        # If the feature doesn't exist, add it from merged_df
        out_df[feature] = merged_df[feature]


out_df.to_csv(f"{outfile}", sep = "\t", index = False)

print(f"CSV Saved to {outfile}")

# Display the merged dataframe 
out_df.head()

Saving to CSV...
CSV Saved to ../data/processed/haunted_places_features_added.tab

,City,Country,Description,Location,State,State_Abbrev,Longitude,Latitude,City_Longitude,City_Latitude,...,Haunted_Places_Witness_Count,Event_Type,Aerodrome_Count,Aerodrome_Proximity,Flight_Intersection_Count,Flight_HighTraffic,Apparition_Type,Time_of_Day,Total_Deaths,Percent_Under_21
0,Ada,United States,Ada witch - Sometimes you can see a misty blue...,Ada Cemetery,Michigan,MI,-85.504893,42.962106,-85.495480,42.960727,...,7,Supernatural | Violence,3,True,56,True,Ghost,Evening,"4,548",2.60%
1,Addison,United States,A little girl was killed suddenly while waitin...,North Adams Rd.,Michigan,MI,-84.381843,41.971425,-84.347168,41.986434,...,1,Violence,0,False,3,False,Unknown,Unknown,"4,548",2.60%
2,Adrian,United States,If you take Gorman Rd. west towards Sand Creek...,Ghost Trestle,Michigan,MI,-84.035656,41.904538,-84.037166,41.897547,...,0,Accident/Disaster | Violence,0,False,5,False,Spirit,Evening,"4,548",2.60%
3,Adrian,United States,"In the 1970's, one room, room 211, in the old ...",Siena Heights University,Michigan,MI,-84.017565,41.905712,-84.037166,41.897547,...,2,Accident/Disaster,0,False,5,False,Unknown,Morning,"4,548",2.60%
4,Albion,United States,Kappa Delta Sorority - The Kappa Delta Sororit...,Albion College,Michigan,MI,-84.745177,42.244006,-84.753030,42.243097,...,1,Accident/Disaster | Supernatural | Violence,0,False,22,True,Unknown,Unknown,"4,548",2.60%

In [3]:
alcohol_abuse_df

                   State Total Deaths % Under 21
0                Alabama        2,208      3.90%
1                 Alaska          433      3.90%
2                Arizona        3,670      2.80%
3               Arkansas        1,407      3.60%
4             California       15,443      2.50%
5               Colorado        2,623      2.80%
6            Connecticut        1,426      2.20%
7               Delaware          466      2.80%
8   District of Columbia          392      3.30%
9                Florida       10,655      2.30%
10               Georgia        3,953      3.70%
11                Hawaii          526      2.30%
12                 Idaho          732      3.00%
13              Illinois        5,151      3.50%
14               Indiana        2,960      3.40%
15                  Iowa        1,305      2.50%
16                Kansas        1,146      3.10%
17              Kentucky        2,206      2.70%
18             Louisiana        2,278      4.10%
19                 Maine          714      1.70%
20              Maryland        2,482      3.20%
21         Massachusetts        2,760      1.90%
22              Michigan        4,548      2.60%
23             Minnesota        2,082      2.30%
24           Mississippi        1,372      3.90%
25              Missouri        2,877      3.70%
26               Montana          605      2.80%
27              Nebraska          720      3.10%
28                Nevada        1,548      2.40%
29         New Hampshire          661      1.70%
30            New Jersey        3,008      2.20%
31            New Mexico        1,581      2.60%
32              New York        6,701      2.00%
33        North Carolina        4,452      3.10%
34          North Dakota          347      2.60%
35                  Ohio        5,739      2.60%
36              Oklahoma        2,104      2.80%
37                Oregon        2,186      2.00%
38          Pennsylvania        5,703      2.70%
39          Rhode Island          493      1.40%
40        South Carolina        2,586      3.20%
41          South Dakota          463      3.90%
42             Tennessee        3,359      2.90%
43                 Texas       10,647      4.00%
44                  Utah          903      3.80%
45               Vermont          332      1.50%
46              Virginia        3,071      3.10%
47            Washington        3,184      1.80%
48         West Virginia        1,037      2.00%
49             Wisconsin        2,651      2.30%
50               Wyoming          347      2.60%