# 4.01 - Jaccard_Distance
## **Haunted Places Witness Count**

- [tika_similarity](http://github.com/chrismattmann/tika-similarity)
    git clone https://github.com/chrismattmann/tika-img-similarity
    pip install tika editdistance
- [ETLLib](http://github.com/chrismattmann/etllib)
    !$ brew install libmagic
    !pip install git+https://github.com/chrismattmann/etllib.git
- CSVKit
    !pip install csvkit==0.9.2


storyPrimaryID
storyID
userID
userPrimaryID
gender
age
title
narrative
media
accountCreateDte
interests

## Convert the TSV dataset into JSON using ETLLib’s tsv2json tool

In [2]:
# System Path #
import os
import sys 

parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(parent_dir)

# Pandas, json and runtime #
import pandas as pd
from tqdm import tqdm
import json
import time
tqdm.pandas()

# Tika #
import tika as tk
from tika import parser

# Iterators #
from collections import Counter
from itertools import chain
import re

# local functions #
from dsci_550_a1.parsingFunctions import extractSequences

os.getcwd()

haunted_places = "../data/processed/haunted_places_features_added.tab"

df = pd.read_csv(haunted_places, sep = "\t")



parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(parent_dir)

from dsci_550_a1.unpack_circles import unpack_cluster

clusters = unpack_cluster("../clustering/jaccard/visualization/clusters.json")

df.loc[clusters['cluster 0']]

,City,Country,Description,Location,State,State_Abbrev,Longitude,Latitude,City_Longitude,City_Latitude,...,Apparition_Type,Time_of_Day,Total_Deaths,Percent_Under_21,Average_Mental_Health_Days,Average_Poor_Health_Days,Depression_Prevalence,Haunted_Place_Proximity,Distance_to_Nearest_Worship,Religion_Intersection
9519,Grand Island,United States,There are several sighting of Ghosts walking a...,Wedgewood's Golf place,Florida,FL,-81.749391,28.878969,-81.728966,28.882489,...,Ghost,Unknown,"10,655",2.30%,4.01,4.90,0.224,True,1536.91,christian
2328,Alhambra,United States,"Students have reported seeing a ""white nun"" ro...",Ramona Convent Secondary School,California,CA,-118.139939,34.073090,-118.127015,34.095287,...,Unknown,Unknown,"15,443",2.50%,4.06,5.67,0.181,True,37.69,NaN
626,Clearfield,United States,In auditorium there are reports by night crews...,Clearfield Middle school,Pennsylvania,PA,-78.482487,40.992690,-78.439188,41.027280,...,Unknown,Evening,"5,703",2.70%,4.63,5.83,0.192,True,1322.24,christian
2956,Prescott,United States,For years many people have seen the ghost of A...,Angeline's Grave,Arizona,AZ,-112.468502,34.540024,-112.468502,34.540024,...,Ghost,Unknown,"3,670",2.80%,4.44,6.02,0.213,True,1125.72,christian
9532,Jacksonville,United States,Traveling slowly down Greenbriar Road late at ...,Greenbriar Light AKA Ghost Light Road,Florida,FL,-81.655651,30.332184,-81.655651,30.332184,...,Ghost,Evening,"10,655",2.30%,4.01,4.90,0.224,True,242.24,christian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6087,Burlington,United States,Urban Legend - It is said that if you go to th...,Stony Hollow,Iowa,IA,-91.111531,40.917408,-91.112890,40.807653,...,Ghost,Unknown,"1,305",2.50%,4.61,5.40,0.227,True,7715.12,christian
2643,Gilroy,United States,There are 2 ghosts that haunt this building. A...,Old Gilroy Hotel,California,CA,-121.570859,37.021416,-121.568275,37.005782,...,Ghost,Unknown,"15,443",2.50%,4.71,5.41,0.239,True,939.60,christian
7500,Norfolk,United States,About 2 years ago a couple was murdered in the...,Gresham Dorms,Virginia,VA,-76.299440,36.887461,-76.285873,36.850769,...,Unknown,Unknown,"3,071",3.10%,4.66,5.60,0.202,True,506.38,christian
7247,Springfield,United States,strange happenings such as doors slamming and ...,prairie capitol convention center,Illinois,IL,-89.644253,39.801085,-89.650148,39.781721,...,Unknown,Evening,"2,960",3.40%,4.30,5.71,0.174,True,471.73,christian
5680,Elkhorn,United States,Reports of a train whistle sounding off when t...,Peck station rd.,Wisconsin,WI,-88.515560,42.739102,-88.544545,42.672793,...,Unknown,Unknown,"2,651",2.30%,4.34,5.00,0.181,True,3165.94,NaN

In [14]:
outfile = "../data/processed/haunted_places_features_added.tab"
columns = pd.read_csv(outfile, nrows = 0, sep = "\t").columns.tolist()

## Subset of files you want to cluster ##
num_files = '' 
while not num_files.isdigit() or not (0 < int(num_files) <= 10992):
    num_files = input("Enter number of haunted places to cluster: ")

num_files = num_files

## subset of fields you want to consider
fields = ''
while True:
    fields = input("Enter a list of fields to keep (e.g., '[\"name\", \"age\"]'): \n\t -a [all fields]").strip()

    # if user puts "a", use all fields 
    if fields == 'a':
        fields = str(columns).replace("'", "\"")
    try:
        fields_check = json.loads(fields)
        if isinstance(fields_check, list):
            if all([(field in columns) for field in json.loads(fields)]):
                break
            else:
                print("Some of the fields you entered are not in {outfile}. Please try again.")

        else:
            print("Incorrect format. Please use json list (e.g., '[\"name\", \"age\"]')")
    except json.JSONDecodeError:
        print("Incorrect format. Please use json list (e.g., '[\"name\", \"age\"]')")

In [ ]:
os.getcwd().split('/').index('232')

ValueError: '232' is not in list

In [ ]:
'/'.join(os.getcwd().split('/')[:7])

'/Users/dgottschalk/Desktop/SP_25/DSCI_550/Assignments'

In [ ]:

# !python ./dsci_550_a1/runJaccardSimilarity.py

# Create circles json
# !python ./tika-img-similarity/tikasimilarity/cluster/edit-cosine-circle-packing.py --inputCSV ./clustering/jaccardSimilarity/jaccard.csv --cluster 2

# Clustering 

# !python ./tika-img-similarity/tikasimilarity/cluster/edit-cosine-cluster.py --inputCSV ./clustering/jaccardSimilarity/jaccard.csv --cluster 2

# !python ./tika-img-similarity/tikasimilarity/cluster/generateLevelCluster.py

# !cp -R ./etllib/html/* . 

#! python -m http.server 8080

# http://localhost:8080/levelCluster-d3.html

In [ ]:
import json
from collections import defaultdict
## pecify keys and default values


# Load cluster json
with open("../clustering/jaccard/visualization/circle.json", "r") as f:
    cluster_data = json.load(f)


# clusters = {}
# # Unpack each cluster and extract file names
# for cluster in cluster_data.get("children", []):
#     # init idx list #
#     data = []

#     for fname in cluster.get("children", []):
#         with open("." + fname["name"].split()[0], "r") as f:
#             haunted_place_data = json.load(f) 
#             data.append(haunted_place_data)
    
#     # save cluster data to cluster dict #
#     clusters[cluster['name']] = data


clusters = defaultdict(list)

for cl in cluster_data.get("children", []):
    clusters[cl['name']] = []
    for fname in cl.get("children", []):

        with open("." + fname["name"].split()[0], "r") as f:
            haunted_place_data = json.load(f) 
            clusters[cl['name']].append(int(haunted_place_data["Haunted_Places_Id"]))
            
df.loc[clusters['cluster 1']]

["Apparition_Type", "Event_Type"]

,City,Country,Description,Location,State,State_Abbrev,Longitude,Latitude,City_Longitude,City_Latitude,...,Apparition_Type,Time_of_Day,Total_Deaths,Percent_Under_21,Average_Mental_Health_Days,Average_Poor_Health_Days,Depression_Prevalence,Haunted_Place_Proximity,Distance_to_Nearest_Worship,Religion_Intersection
10308,Hartford,United States,"Built in 1796, the former State Capitol buildi...",Old State House,Connecticut,CT,-72.672680,41.766096,-72.685093,41.763711,...,"Ghost, Spirit",Evening,"1,426",2.20%,NaN,NaN,NaN,True,697.53,christian
3542,New Orleans,United States,A ghost called Julhunts the place. People see ...,Bottom of the Cup Tea Room,Louisiana,LA,-90.066345,29.954849,-90.071532,29.951066,...,Ghost,Unknown,"2,278",4.10%,NaN,NaN,NaN,True,593.46,christian
9080,Houston,United States,An old teacher who was accused of abusing chil...,Fiesta Elementary School,Texas,TX,-95.455012,29.666632,-95.369803,29.760427,...,Unknown,Evening,"10,647",4.00%,NaN,NaN,NaN,True,1109.66,christian
10308,Hartford,United States,"Built in 1796, the former State Capitol buildi...",Old State House,Connecticut,CT,-72.672680,41.766096,-72.685093,41.763711,...,"Ghost, Spirit",Evening,"1,426",2.20%,NaN,NaN,NaN,True,697.53,christian
656,Drexel Hill,United States,"Now, next to the school there is a WAWA. Many,...",Garretford Elementary School,Pennsylvania,PA,-75.297875,39.943467,-75.292130,39.947057,...,Unknown,Morning,"5,703",2.70%,NaN,NaN,NaN,True,2173.30,christian
10308,Hartford,United States,"Built in 1796, the former State Capitol buildi...",Old State House,Connecticut,CT,-72.672680,41.766096,-72.685093,41.763711,...,"Ghost, Spirit",Evening,"1,426",2.20%,NaN,NaN,NaN,True,697.53,christian
10596,Beaufort,United States,This notorious church is located on St. Helena...,The Chapel of Ease,South Carolina,SC,-80.576774,32.375473,-80.669829,32.431581,...,Unknown,Morning,"2,586",3.20%,NaN,NaN,NaN,True,21.75,christian
10308,Hartford,United States,"Built in 1796, the former State Capitol buildi...",Old State House,Connecticut,CT,-72.672680,41.766096,-72.685093,41.763711,...,"Ghost, Spirit",Evening,"1,426",2.20%,NaN,NaN,NaN,True,697.53,christian
3542,New Orleans,United States,A ghost called Julhunts the place. People see ...,Bottom of the Cup Tea Room,Louisiana,LA,-90.066345,29.954849,-90.071532,29.951066,...,Ghost,Unknown,"2,278",4.10%,NaN,NaN,NaN,True,593.46,christian
6125,Decorah,United States,Supposedly you can see people in the upstairs ...,Porter House Museum,Iowa,IA,-91.789953,43.302139,-91.785709,43.303306,...,Unknown,Unknown,"1,305",2.50%,NaN,NaN,NaN,True,154.62,christian
9080,Houston,United States,An old teacher who was accused of abusing chil...,Fiesta Elementary School,Texas,TX,-95.455012,29.666632,-95.369803,29.760427,...,Unknown,Evening,"10,647",4.00%,NaN,NaN,NaN,True,1109.66,christian
656,Drexel Hill,United States,"Now, next to the school there is a WAWA. Many,...",Garretford Elementary School,Pennsylvania,PA,-75.297875,39.943467,-75.292130,39.947057,...,Unknown,Morning,"5,703",2.70%,NaN,NaN,NaN,True,2173.30,christian
3542,New Orleans,United States,A ghost called Julhunts the place. People see ...,Bottom of the Cup Tea Room,Louisiana,LA,-90.066345,29.954849,-90.071532,29.951066,...,Ghost,Unknown,"2,278",4.10%,NaN,NaN,NaN,True,593.46,christian
656,Drexel Hill,United States,"Now, next to the school there is a WAWA. Many,...",Garretford Elementary School,Pennsylvania,PA,-75.297875,39.943467,-75.292130,39.947057,...,Unknown,Morning,"5,703",2.70%,NaN,NaN,NaN,True,2173.30,christian
9080,Houston,United States,An old teacher who was accused of abusing chil...,Fiesta Elementary School,Texas,TX,-95.455012,29.666632,-95.369803,29.760427,...,Unknown,Evening,"10,647",4.00%,NaN,NaN,NaN,True,1109.66,christian
6125,Decorah,United States,Supposedly you can see people in the upstairs ...,Porter House Museum,Iowa,IA,-91.789953,43.302139,-91.785709,43.303306,...,Unknown,Unknown,"1,305",2.50%,NaN,NaN,NaN,True,154.62,christian
9080,Houston,United States,An old teacher who was accused of abusing chil...,Fiesta Elementary School,Texas,TX,-95.455012,29.666632,-95.369803,29.760427,...,Unknown,Evening,"10,647",4.00%,NaN,NaN,NaN,True,1109.66,christian
9080,Houston,United States,An old teacher who was accused of abusing chil...,Fiesta Elementary School,Texas,TX,-95.455012,29.666632,-95.369803,29.760427,...,Unknown,Evening,"10,647",4.00%,NaN,NaN,NaN,True,1109.66,christian

In [ ]:
import json
import pandas as pd


# Load JSON file
with open("../clustering/jaccard/visualization/circle.json", "r") as f:
    data = json.load(f)

# Function to extract haunted_place_Id values
def extract_haunted_place_ids(data):
    ids = []
    if isinstance(data, dict):
        if "Haunted_Places_Id" in data:
            ids.append(data["Haunted_Places_ID"])
        if "children" in data:
            for child in data.get("children", []):
                ids.extend(extract_haunted_place_ids(child))
    return ids

# Extract IDs and convert to DataFrame
haunted_place_ids = extract_haunted_place_ids(data)
df = pd.DataFrame(haunted_place_ids, columns=["haunted_place_Id"])

# Display the DataFrame
print(df)

Empty DataFrame
Columns: [haunted_place_Id]
Index: []

In [ ]:
with open("../clustering/jaccard/visualization/clusters.json", "r") as f:
    data = json.load(f)

clusters = {}

for cl in data.get("children", []):
    clusters[cl['name']] = []
    for entry in cl.get("children", []):
        with open("." + entry['name'].split()[0], 'r') as haunted_place:
            idx = int(json.load(haunted_place)["Haunted_Places_Id"])
            clusters[cl['name']].append(idx)
print(clusters)

{'cluster 0': [9519, 2328, 626, 2956, 9532, 7918, 3546, 6334, 2410, 7390, 4058, 10676, 6031, 1907, 4472, 6877, 947, 7564, 4800, 415, 6226, 7947, 9214, 5354, 10799, 3921, 7904, 6814, 8691, 6278, 5826, 9836, 8656, 5680, 3001, 10333, 1889, 9499, 6535, 5309, 4915, 3181, 910, 1728, 7500, 7247, 6896, 2328, 626, 7613, 7918, 6334, 2410, 7028, 9550, 10676, 4472, 6877, 3349, 1449, 1277, 7564, 4800, 415, 6226, 5354, 10730, 8696, 6814, 9836, 8656, 5680, 8113, 6721, 3747, 8784, 5161, 10106, 957, 8289, 10333, 1889, 1875, 3499, 4915, 910, 7500, 7247, 7185, 7613, 77, 2956, 7918, 7390, 4058, 7028, 9550, 10676, 6031, 1907, 6877, 3349, 602, 947, 1277, 7564, 4800, 83, 6226, 7947, 9557, 10730, 3876, 1980, 9836, 5680, 6203, 684, 6412, 6721, 4027, 3001, 5161, 957, 8289, 5309, 3181, 910, 2643, 1728, 2195, 10805, 2956, 9532, 6334, 4058, 6031, 5287, 3349, 602, 1277, 4800, 415, 6226, 7947, 5354, 9557, 10799, 8696, 1980, 2991, 8691, 1530, 5883, 9836, 684, 8113, 6721, 3747, 10106, 8289, 10452, 1889, 6535, 5309, 1875, 8898, 3181, 910, 626, 9532, 6334, 4058, 5287, 1907, 1277, 7564, 4800, 9557, 10730, 10799, 9158, 1076, 1980, 6278, 10848, 9836, 8656, 8784, 10106, 10333, 9499, 3181, 6087, 1434, 6896, 9532, 6334, 987, 6031, 4472, 83, 9557, 10799, 1076, 1530, 5417, 5826, 10848, 9836, 1542, 5161, 10106, 8289, 10452, 1889, 9499, 910, 6087, 1449, 7564, 83, 415, 7947, 9557, 10799, 9158, 7904, 7618, 1530, 5417, 5883, 9836, 8656, 684, 6721, 8784, 4027, 3001, 5161, 8289, 10452, 1889, 9499, 910, 10805, 2956, 3546, 6334, 2410, 4058, 9550, 4472, 1449, 947, 1277, 9557, 7618, 8691, 5826, 10848, 684, 1542, 4027, 3001, 957, 8289, 10452, 9499, 8898, 1434, 2956, 7918, 3546, 2410, 7390, 7028, 987, 10676, 6031, 5287, 1907, 6877, 3349, 602, 4800, 83, 7947, 5354, 10730, 9158, 1076, 1980, 7904, 6814, 2991, 1530, 5826, 9836, 5680, 684, 8113, 1542, 4027, 3001, 5161, 957, 8289, 10452, 9499, 5309, 4915, 8898, 6087, 2643, 4452, 1728, 2195, 1434, 2956, 7918, 3546, 6334, 7390, 9550, 10676, 5287, 1907, 7564, 4800, 83, 6226, 3876, 9158, 1980, 2991, 7618, 6278, 5417, 10848, 9836, 8656, 5680, 684, 8113, 6721, 8784, 1542, 8289, 10452, 6535, 5309, 1875, 3181, 910, 2643, 1728, 7500, 7918, 4058, 7028, 9219, 987, 9550, 6031, 1907, 6877, 602, 4800, 9214, 5354, 9557, 10730, 10799, 3876, 9158, 7904, 7618, 1530, 5417, 5883, 10848, 684, 8784, 8289, 10452, 10333, 6535, 4915, 3181, 4452, 7247, 6896, 3546, 7390, 7028, 10676, 6031, 1907, 6877, 3349, 1449, 602, 7564, 4800, 7947, 9214, 5354, 9557, 10730, 9158, 1076, 2991, 7618, 8691, 1530, 6278, 5417, 10848, 9836, 8656, 5680, 4027, 3001, 5161, 10106, 957, 8289, 10452, 1889, 5309, 3499, 4915, 3181, 2643, 4452, 1728, 7500, 7247, 7701, 1434, 6896, 3546, 9219, 987, 4472, 1449, 7564, 6226, 9214, 9158, 1076, 1530, 5417, 5883, 5826, 10848, 9836, 684, 6721, 1542, 4027, 3001, 5161, 10106, 957, 8289, 6535, 5309, 1875, 8898, 910, 6087, 2643, 7247, 1434, 6334, 7390, 7028, 987, 1907, 6877, 602, 947, 4800, 83, 7947, 9214, 5354, 9557, 10799, 3876, 8696, 9158, 6814, 8691, 6278, 5883, 8656, 6203, 6412, 6721, 8784, 3001, 8289, 10333, 9499, 6535, 1875, 3499, 4915, 8898, 910, 7500, 7701, 2195, 1434, 6896, 7390, 4058, 987, 10676, 6031, 1907, 3349, 1449, 602, 7564, 4800, 83, 415, 9214, 9557, 10730, 3921, 1980, 2991, 8691, 1530, 6278, 10848, 5680, 6203, 8113, 8784, 1542, 4027, 3001, 5161, 10106, 957, 1889, 9499, 6535, 3499, 8898, 910, 7701, 2195, 6896, 7390, 4058, 9219, 9550, 6031, 3349, 602, 83, 5354, 9557, 6814, 6278, 9836, 8656, 5680, 8113, 6721, 8784, 10333, 1875, 8898, 7247, 7701, 2195, 1434, 83, 6226, 9214, 9557, 9158, 1530, 5883, 5826, 10848, 9836, 8656, 8784, 1542, 5161, 10106, 957, 1889, 9499, 6535, 5309, 1875, 8898, 1434, 7028, 5287, 1449, 7564, 6226, 9214, 10730, 3876, 9158, 1980, 7904, 2991, 7618, 6278, 5417, 8656, 6203, 3747, 8289, 10452, 3499, 4915, 8898, 2643, 4452, 7247, 7701, 2195, 947, 83, 6226, 7947, 9214, 9557, 9158, 7904, 7618, 5417, 9836, 8656, 684, 3001, 10452, 1875, 8898, 910, 6087, 2643, 987, 9550, 10676, 6031, 1907, 1449, 1277, 4800, 415, 5354, 10799, 9158, 1980, 7904, 7618, 8691, 9836, 5680, 6203, 684, 8113, 6721, 8784, 3001, 5161, 957, 8289, 10333, 1889, 6535, 3499, 4915, 6087, 1728, 7500, 1434, 6896, 9550, 10676, 5287, 1907, 602, 1277, 7564, 415, 6226, 5354, 10730, 9158, 3921, 7904, 6814, 8691, 6278, 10848, 9836, 6203, 684, 8113, 6412, 6721, 3747, 5161, 8289, 10452, 10333, 1889, 6535, 5309, 8898, 2643, 4452, 2195, 6031, 5287, 4472, 1449, 602, 947, 1277, 4800, 6226, 7947, 5354, 9557, 8696, 9158, 1076, 3921, 1980, 1530, 6278, 8656, 5680, 6203, 684, 8113, 6412, 6721, 3001, 5161, 957, 8289, 10452, 10333, 1889, 9499, 5309, 3499, 8898, 910, 4452, 1728, 1434, 6896, 6031, 1449, 947, 1277, 7564, 83, 7947, 9557, 7904, 1530, 5883, 5826, 8656, 684, 6721, 1542, 3001, 10106, 8289, 1889, 9499, 6535, 5309, 2643, 7247, 1434, 5287, 1907, 4472, 6877, 602, 1277, 4800, 5354, 3876, 8696, 1076, 3921, 1980, 7904, 7618, 8691, 1530, 5417, 8656, 8113, 6412, 957, 6535, 3499, 4915, 8898, 910, 2643, 4452, 2195, 83, 415, 6226, 9214, 1076, 1530, 5883, 5161, 1889, 7500, 947, 415, 7947, 10799, 1076, 7618, 1530, 5826, 684, 6721, 1542, 10106, 8289, 1889, 5309, 1875, 2643, 7500, 6877, 3349, 1449, 602, 1277, 4800, 83, 415, 9214, 9557, 10730, 10799, 8696, 1076, 6814, 7618, 8691, 1530, 6278, 5417, 9836, 8656, 684, 8113, 6721, 3747, 10452, 10333, 9499, 1875, 4915, 8898, 910, 1728, 2195, 1434, 1449, 947, 83, 6226, 10799, 9158, 1076, 7904, 8691, 1530, 5826, 9836, 8656, 684, 6721, 1542, 3001, 5161, 957, 8289, 10452, 1889, 6535, 5309, 1875, 8898, 6087, 1449, 1277, 7564, 83, 415, 7947, 10799, 7618, 1530, 10848, 8656, 8113, 3001, 5161, 957, 8289, 10452, 1889, 9499, 6535, 1875, 910, 2643, 7500, 602, 1277, 83, 415, 6226, 9214, 10799, 8696, 7904, 6814, 8691, 5417, 5883, 9836, 6203, 684, 6721, 3747, 8784, 4027, 957, 10452, 10333, 9499, 6535, 5309, 3499, 4915, 3181, 910, 2643, 4452, 2195, 1277, 9214, 9557, 9158, 1076, 7904, 5883, 10848, 8656, 684, 8113, 3001, 10452, 5309, 1875, 8898, 7500, 1434, 1277, 7564, 4800, 83, 9214, 10730, 8696, 9158, 1076, 2991, 1530, 10848, 9836, 8113, 6535, 5309, 1875, 910, 6087, 2643, 4452, 1728, 7247, 2195, 6896, 83, 7947, 10799, 9158, 1980, 8691, 6203, 1542, 4027, 5161, 10106, 957, 6535, 4915, 3181, 910, 7500, 7247, 7701, 2195, 6896, 6226, 9557, 3876, 6814, 2991, 8691, 5417, 5826, 10848, 5680, 684, 8113, 6412, 6721, 3747, 8784, 4027, 3001, 3499, 910, 1728, 7247, 7947, 10799, 9158, 1076, 8691, 1530, 5883, 5826, 10848, 9836, 8656, 6721, 8784, 4027, 3001, 5161, 10106, 957, 10452, 5309, 1875, 910, 7247, 415, 6226, 7947, 9214, 10730, 10799, 3876, 8696, 3921, 1980, 7904, 2991, 7618, 8691, 1530, 5883, 9836, 684, 3747, 8784, 4027, 957, 8289, 10452, 1889, 9499, 6535, 2195, 9214, 5354, 9557, 9158, 1980, 7904, 6814, 6278, 5417, 5883, 5826, 684, 8113, 3747, 1542, 9499, 6535, 1875, 4915, 3181, 7247, 2195, 9557, 3876, 2991, 5417, 10848, 8113, 6412, 3747, 8784, 10106, 9499, 6535, 1875, 4452, 1728, 9214, 10730, 3921, 1980, 6278, 8656, 5161, 957, 10333, 1889, 6535, 5309, 8898, 6087, 2195, 1530, 6278, 5417, 10848, 5680, 8113, 6412, 3747, 3001, 5161, 10106, 957, 8289, 10452, 1889, 3499, 4915, 8898, 3181, 910, 1728, 2195, 9158, 1076, 8691, 1530, 5417, 10848, 9836, 8656, 684, 8113, 6721, 1542, 3001, 10106, 957, 8289, 1889, 9499, 1434, 3876, 8696, 9158, 3921, 7904, 6814, 2991, 8691, 10848, 6203, 684, 8113, 6412, 1542, 10333, 6535, 5309, 1875, 3499, 3181, 910, 6087, 4452, 1728, 7500, 7247, 7701, 2195, 10799, 9158, 7904, 8691, 5417, 5883, 5826, 9836, 8656, 684, 8113, 6721, 8784, 3001, 8289, 10452, 1889, 910, 6087, 7500, 7247, 3876, 8696, 9158, 1076, 1530, 5417, 9836, 6203, 684, 8113, 6721, 8784, 5161, 10106, 957, 10452, 6535, 5309, 2643, 1728, 7247, 7904, 7618, 1530, 5883, 10848, 8656, 684, 1542, 4027, 3001, 5161, 10106, 957, 10452, 1889, 5309, 1875, 6087, 7247, 1434, 9158, 1076, 7904, 8691, 1530, 10848, 9836, 684, 8113, 6721, 8784, 5161, 10106, 957, 9499, 6535, 8898, 6087, 1434, 3921, 1980, 7904, 6814, 8691, 1530, 5417, 8656, 1542, 4027, 10106, 957, 10452, 9499, 6535, 5309, 4915, 6087, 2643, 7701, 2195, 6896, 7904, 6814, 8691, 1530, 6278, 5883, 5826, 9836, 5680, 684, 8113, 6412, 3747, 8784, 1542, 4027, 5161, 10106, 957, 10452, 6535, 3499, 4915, 4452, 1728, 7701, 2195, 7618, 8691, 1530, 10848, 8656, 684, 3001, 5161, 10106, 8289, 9499, 6535, 1875, 6087, 7500, 7247, 1434, 1530, 5417, 5826, 10848, 9836, 684, 8113, 6721, 8784, 1542, 3001, 10106, 957, 1889, 6535, 2643, 7500, 1434, 6814, 5417, 5680, 1542, 5161, 10106, 957, 9499, 5309, 8898, 3181, 910, 6087, 2643, 4452, 7247, 7701, 1530, 5417, 5883, 5826, 10848, 9836, 8113, 6721, 1542, 3001, 5161, 957, 8289, 6535, 5309, 8898, 7500, 1434, 5417, 5883, 9836, 6721, 8784, 1542, 3001, 5161, 10106, 1889, 6535, 1875, 6087, 2643, 7247, 1434, 6278, 5417, 5826, 10848, 9836, 6203, 6721, 3747, 8784, 1542, 3001, 5161, 10106, 957, 8289, 10452, 9499, 8898, 6087, 2643, 4452, 1728, 7247, 7701, 2195, 6896, 1530, 6278, 5417, 5883, 5826, 10848, 9836, 5680, 684, 8113, 6721, 3001, 10106, 957, 10452, 10333, 6535, 5309, 1875, 6087, 2643, 4452, 1728, 7701, 1434, 6278, 10848, 9836, 6203, 684, 8113, 6412, 3747, 957, 1889, 9499, 6535, 1875, 3499, 4452, 1728, 7500, 7247, 1434, 6896, 5883, 10848, 8656, 684, 6721, 8784, 1542, 6535, 8898, 6087, 2643, 7500, 7247, 5680], 'cluster 1': [9706, 1494, 7185, 7613, 77, 10805, 7028, 9219, 987, 9550, 5287, 3349, 602, 1277, 83, 9557, 10730, 3876, 8696, 9158, 1076, 1980, 2991, 7618, 1530, 5417, 5883, 10848, 6203, 684, 8113, 6412, 6721, 3747, 8784, 1542, 4027, 5161, 10106, 957, 8289, 10452, 1875, 3499, 8898, 6087, 2643, 4452, 7701, 2195, 1434, 9706, 1494, 7185, 77, 10805, 2956, 9532, 3546, 7390, 4058, 9219, 987, 6031, 5287, 1907, 602, 947, 83, 9214, 3876, 9158, 1076, 3921, 1980, 7904, 2991, 7618, 8691, 1530, 6278, 5417, 5883, 10848, 6203, 684, 6412, 1542, 4027, 3001, 10452, 6535, 5309, 8898, 3181, 6087, 2643, 4452, 1728, 7701, 2195, 1434, 6896, 9706, 1494, 626, 10805, 9532, 3546, 6334, 2410, 9219, 987, 5287, 4472, 1449, 415, 9214, 5354, 10799, 8696, 9158, 1076, 3921, 7904, 6814, 2991, 8691, 1530, 6278, 5417, 5883, 5826, 10848, 8656, 8113, 3747, 8784, 1542, 10106, 10452, 10333, 1889, 9499, 6535, 1875, 3499, 4915, 8898, 6087, 4452, 7500, 7247, 7701, 1434, 6896, 1494, 626, 7185, 7613, 77, 7918, 3546, 2410, 7390, 7028, 9219, 987, 9550, 10676, 1907, 4472, 6877, 1449, 947, 7564, 83, 9214, 10730, 3876, 9158, 1076, 3921, 7904, 6814, 7618, 6278, 5417, 5826, 10848, 5680, 6203, 6412, 8784, 1542, 4027, 3001, 5161, 957, 10333, 9499, 3499, 4915, 6087, 2643, 4452, 1728, 7500, 7701, 2195, 1434, 6896, 7185, 7613, 77, 10805, 2956, 7918, 3546, 2410, 7390, 7028, 9219, 987, 9550, 10676, 6031, 4472, 6877, 3349, 1449, 602, 947, 83, 415, 6226, 7947, 9214, 5354, 3876, 8696, 3921, 7904, 6814, 2991, 7618, 8691, 1530, 5883, 5826, 5680, 6203, 684, 8113, 6412, 6721, 3747, 1542, 4027, 3001, 5161, 957, 8289, 10452, 1889, 6535, 5309, 1875, 3499, 4915, 8898, 2643, 4452, 1728, 7500, 7247, 7701, 2195, 7185, 77, 10805, 2956, 3546, 2410, 4058, 9219, 9550, 10676, 5287, 1449, 947, 1277, 7564, 4800, 415, 6226, 7947, 9214, 3876, 9158, 1980, 7904, 7618, 8691, 6278, 5883, 8656, 5680, 6203, 684, 8113, 6721, 8784, 4027, 3001, 957, 6535, 5309, 1875, 3499, 8898, 3181, 2643, 7500, 7247, 7701, 2195, 1434, 77, 10805, 2956, 9532, 3546, 6334, 2410, 7390, 4058, 7028, 9219, 987, 9550, 10676, 6031, 4472, 6877, 602, 947, 1277, 4800, 6226, 9214, 1076, 1980, 2991, 8691, 6278, 5826, 10848, 5680, 6203, 8113, 6412, 3747, 1542, 10106, 957, 10333, 6535, 5309, 1875, 3499, 4915, 8898, 6087, 2643, 7500, 7247, 7701, 2195, 1434, 77, 9532, 7390, 7028, 9219, 987, 6031, 5287, 1907, 3349, 602, 7564, 4800, 83, 415, 6226, 7947, 9214, 10799, 9158, 1076, 3921, 7904, 2991, 1530, 5417, 5883, 9836, 8656, 5680, 6203, 8113, 6412, 6721, 8784, 5161, 10106, 10333, 1889, 6535, 5309, 1875, 3181, 910, 6087, 2643, 4452, 1728, 7500, 7247, 2195, 10805, 9532, 6334, 4058, 9219, 4472, 1449, 947, 1277, 7564, 415, 6226, 9214, 9557, 10799, 3876, 8696, 3921, 7618, 8691, 6278, 5417, 5883, 10848, 8656, 6203, 6412, 6721, 3747, 10106, 10333, 1889, 6535, 1875, 3499, 3181, 910, 7247, 7701, 6896, 9532, 2410, 7028, 9219, 987, 6031, 4472, 6877, 3349, 1449, 602, 1277, 415, 7947, 9214, 5354, 10730, 10799, 8696, 1076, 3921, 7904, 6814, 8691, 1530, 5826, 6203, 6412, 3747, 4027, 5161, 10106, 957, 10333, 1889, 3499, 4915, 8898, 6087, 4452, 7247, 7701, 2195, 6896, 9532, 6334, 2410, 7390, 10676, 5287, 4472, 3349, 1449, 947, 1277, 83, 415, 6226, 7947, 8696, 1076, 3921, 1980, 6814, 2991, 8691, 6278, 5826, 9836, 8656, 5680, 6203, 8113, 6412, 6721, 3747, 1542, 4027, 3001, 5161, 10106, 957, 9499, 5309, 1875, 3499, 8898, 910, 1728, 7500, 7701, 2195, 1434, 7918, 6334, 2410, 4058, 9219, 987, 9550, 5287, 4472, 947, 1277, 83, 415, 6226, 10799, 3876, 8696, 3921, 1980, 7904, 6814, 5883, 5826, 6203, 684, 8113, 6412, 6721, 3747, 8784, 1542, 10333, 9499, 6535, 1875, 8898, 910, 6087, 2195, 6334, 2410, 4058, 9550, 6031, 947, 1277, 4800, 83, 415, 7947, 5354, 9557, 10799, 3876, 8696, 1980, 7904, 6814, 2991, 7618, 8691, 6278, 8656, 5680, 8113, 8784, 10452, 10333, 1889, 9499, 3499, 4915, 4452, 1728, 7500, 6896, 2410, 4058, 9219, 9550, 10676, 6031, 5287, 4472, 3349, 1449, 1277, 7564, 415, 6226, 10730, 1076, 3921, 1980, 7904, 2991, 7618, 1530, 5417, 5826, 10848, 9836, 5680, 684, 8113, 3747, 1542, 4027, 5161, 10106, 957, 10452, 1889, 5309, 3181, 2643, 4452, 1728, 7247, 2410, 7028, 9219, 9550, 5287, 4472, 6877, 947, 1277, 6226, 7947, 5354, 10799, 3876, 8696, 9158, 1076, 7904, 6814, 7618, 5417, 5883, 5826, 9836, 8656, 684, 6412, 6721, 3747, 8289, 10452, 10333, 5309, 1875, 4915, 3181, 6087, 2643, 4452, 1728, 7500, 7247, 1434, 7028, 987, 10676, 5287, 1907, 4472, 6877, 1449, 947, 1277, 4800, 6226, 7947, 9214, 10730, 10799, 3876, 8696, 9158, 3921, 1980, 7904, 2991, 7618, 8691, 1530, 5417, 5883, 5826, 10848, 6203, 684, 6412, 3747, 1542, 4027, 3001, 5161, 10106, 957, 8289, 10452, 9499, 6535, 3499, 4915, 3181, 910, 4452, 1728, 7500, 6896, 4058, 9219, 987, 9550, 6031, 1907, 4472, 6877, 3349, 1449, 947, 1277, 7564, 415, 7947, 10799, 1076, 3921, 7904, 7618, 8691, 5417, 6203, 684, 8113, 6721, 4027, 3001, 8289, 10452, 10333, 3499, 910, 6087, 2643, 7500, 7247, 9219, 987, 9550, 10676, 6031, 1907, 4472, 6877, 3349, 602, 1277, 4800, 83, 415, 7947, 5354, 8696, 1076, 3921, 6814, 8691, 1530, 5883, 5826, 10848, 9836, 5680, 684, 8113, 6412, 6721, 8784, 1542, 3001, 5161, 10106, 957, 10333, 1889, 6535, 5309, 1875, 3181, 910, 6087, 1728, 7500, 6896, 9219, 987, 9550, 10676, 6031, 5287, 4472, 3349, 1449, 1277, 7564, 415, 10799, 8696, 1076, 3921, 6814, 8691, 1530, 5883, 5826, 10848, 8113, 6721, 8784, 1542, 4027, 5161, 10106, 957, 8289, 1889, 9499, 6535, 5309, 4915, 7500, 7247, 7701, 2195, 1434, 6896, 5287, 4472, 6877, 3349, 602, 947, 7564, 83, 6226, 7947, 9214, 9557, 10730, 3876, 8696, 1076, 3921, 6814, 2991, 1530, 6278, 5417, 5883, 5826, 10848, 8656, 6412, 3747, 1542, 4027, 10106, 10452, 9499, 5309, 1875, 8898, 3181, 910, 2643, 4452, 7247, 7701, 2195, 6031, 4472, 6877, 3349, 1449, 947, 4800, 83, 7947, 9214, 9557, 3876, 8696, 1076, 1980, 2991, 7618, 1530, 5417, 5826, 8656, 5680, 8784, 1542, 4027, 3001, 10106, 957, 1875, 3499, 4915, 3181, 910, 6087, 1728, 7500, 7247, 7701, 6896, 10676, 1907, 6877, 3349, 7564, 83, 415, 9214, 10730, 10799, 3876, 7904, 6814, 2991, 7618, 8691, 5417, 5883, 5826, 10848, 9836, 3747, 8784, 1542, 4027, 10106, 6535, 1875, 4915, 3181, 6087, 2643, 7500, 7247, 7701, 2195, 1907, 4472, 6877, 415, 6226, 9214, 5354, 10799, 9158, 1076, 3921, 7618, 8691, 5417, 10848, 9836, 5680, 8113, 6412, 8784, 4027, 5161, 957, 10452, 1875, 8898, 910, 6087, 4452, 1728, 7500, 7701, 2195, 6896, 3349, 1449, 947, 7564, 83, 415, 6226, 7947, 9214, 10730, 10799, 9158, 6814, 2991, 6278, 10848, 9836, 5680, 6203, 684, 6721, 3747, 8784, 1542, 4027, 3001, 5161, 10106, 8289, 10452, 10333, 1889, 5309, 1875, 3181, 6087, 1728, 7500, 7247, 7701, 1434, 6896, 4472, 1449, 602, 947, 1277, 7564, 4800, 7947, 5354, 9557, 10730, 10799, 9158, 1980, 7904, 6814, 7618, 8691, 5417, 5826, 10848, 9836, 8656, 5680, 684, 8113, 6412, 6721, 8784, 1542, 4027, 3001, 10106, 957, 8289, 10452, 9499, 6535, 5309, 1875, 8898, 3181, 910, 6087, 2643, 4452, 7247, 1434, 4472, 3349, 1449, 1277, 7564, 83, 6226, 9214, 9557, 10730, 9158, 7904, 6814, 8691, 5417, 5883, 10848, 9836, 8656, 5680, 8113, 8784, 4027, 3001, 5161, 957, 10452, 10333, 9499, 6535, 8898, 910, 6087, 7247, 1434, 6896, 947, 7564, 6226, 7947, 5354, 3876, 9158, 3921, 1980, 7904, 2991, 5883, 5826, 10848, 5680, 6203, 6412, 8784, 1542, 4027, 3001, 5161, 10106, 957, 8289, 1889, 6535, 5309, 3499, 3181, 6087, 2643, 4452, 7500, 7247, 7701, 6896, 602, 1277, 7564, 4800, 415, 7947, 9214, 9557, 3876, 8696, 3921, 1980, 6814, 2991, 7618, 5417, 5883, 10848, 5680, 8113, 6412, 8784, 4027, 10106, 10333, 9499, 4915, 910, 2643, 7500, 7247, 7701, 1434, 602, 947, 4800, 6226, 9214, 9557, 3876, 9158, 1076, 3921, 7904, 6814, 2991, 8691, 5417, 5883, 5826, 9836, 5680, 6203, 684, 6412, 6721, 8784, 1542, 4027, 10106, 5309, 8898, 6087, 4452, 7247, 7701, 1434, 947, 7564, 4800, 7947, 5354, 9557, 10730, 3876, 9158, 1076, 3921, 1980, 2991, 7618, 1530, 6278, 5826, 10848, 8656, 5680, 8113, 6412, 1542, 3001, 5161, 8289, 1889, 1875, 8898, 6087, 1728, 7500, 7247, 7701, 1434, 6896, 947, 7564, 4800, 83, 415, 6226, 7947, 10799, 3876, 8696, 6814, 7618, 8691, 1530, 6278, 5417, 5826, 9836, 6203, 6412, 6721, 8784, 1542, 4027, 5161, 10106, 957, 8289, 10333, 1889, 9499, 6535, 3499, 3181, 910, 6087, 2643, 4452, 7247, 6896, 415, 6226, 7947, 5354, 10799, 3876, 3921, 1980, 7904, 6814, 7618, 8691, 6278, 5417, 5883, 8656, 5680, 6203, 684, 6412, 6721, 3747, 8784, 1542, 5161, 10106, 957, 8289, 10452, 10333, 1889, 9499, 3499, 4915, 8898, 3181, 7500, 7701, 1434, 4800, 6226, 9214, 5354, 9557, 10730, 3876, 8696, 1076, 3921, 7904, 6814, 2991, 7618, 1530, 6278, 5417, 5883, 5826, 10848, 9836, 8656, 5680, 684, 8113, 6412, 6721, 3747, 8784, 3001, 8289, 10452, 10333, 9499, 5309, 1875, 3499, 8898, 6087, 4452, 1728, 1434, 4800, 83, 415, 7947, 9214, 5354, 10730, 10799, 8696, 9158, 1076, 3921, 1980, 7904, 7618, 1530, 6278, 5883, 9836, 8656, 6203, 1542, 5161, 10106, 957, 8289, 10452, 10333, 9499, 6535, 5309, 1875, 4915, 8898, 3181, 2643, 4452, 7500, 7701, 2195, 1434, 6896, 83, 415, 6226, 9214, 9557, 3876, 3921, 7904, 6814, 2991, 7618, 5417, 684, 8113, 6412, 3747, 1542, 8289, 1889, 9499, 6535, 3499, 8898, 6087, 2643, 4452, 1728, 7500, 7701, 2195, 1434, 6896, 5354, 9557, 9158, 1076, 6814, 6278, 5417, 5826, 10848, 8656, 5680, 6203, 8113, 6412, 1542, 3001, 5161, 10106, 10333, 5309, 3499, 4915, 8898, 3181, 910, 6087, 2643, 4452, 1728, 7500, 7247, 7701, 1434, 6896, 6226, 7947, 10730, 10799, 3876, 8696, 1076, 3921, 2991, 7618, 8691, 1530, 10848, 9836, 8656, 5680, 6203, 6412, 6721, 8784, 4027, 3001, 5161, 10106, 957, 8289, 10452, 10333, 1889, 3499, 8898, 910, 4452, 1728, 7500, 7701, 1434, 6896, 7947, 9214, 5354, 10730, 10799, 8696, 9158, 1076, 3921, 1980, 7904, 6814, 7618, 8691, 1530, 6278, 5883, 5826, 9836, 8656, 5680, 6203, 684, 6721, 1542, 4027, 3001, 5161, 957, 8289, 10452, 10333, 1889, 5309, 3499, 4915, 8898, 3181, 910, 6087, 2643, 7500, 7247, 7701, 2195, 1434, 6896, 5354, 10799, 3876, 8696, 9158, 1076, 7904, 6814, 2991, 7618, 8691, 1530, 5417, 10848, 9836, 5680, 6203, 684, 8113, 6412, 6721, 3747, 8784, 1542, 10106, 8289, 10452, 1875, 3499, 4915, 3181, 910, 2643, 4452, 1728, 7500, 7247, 7701, 6896, 5354, 9557, 10730, 10799, 3876, 8696, 9158, 1076, 3921, 1980, 7904, 6814, 2991, 7618, 5883, 5826, 9836, 8656, 6203, 684, 6721, 1542, 4027, 10333, 9499, 6535, 5309, 1875, 6087, 2643, 4452, 7247, 7701, 1434, 6896, 9557, 10799, 3921, 1980, 7904, 7618, 6278, 5883, 5826, 6412, 3747, 8784, 4027, 5161, 10452, 6535, 5309, 1875, 3499, 4915, 8898, 910, 6087, 2643, 4452, 1728, 7500, 7247, 6896, 10730, 1076, 1980, 7618, 1530, 6278, 5417, 9836, 8656, 5680, 6721, 3747, 8784, 3001, 5161, 10106, 957, 8289, 10452, 1889, 4915, 8898, 2643, 6896, 1076, 1980, 2991, 7618, 1530, 10848, 3747, 1542, 4027, 5161, 10106, 957, 9499, 6535, 5309, 1875, 4915, 8898, 3181, 2643, 1728, 7701, 2195, 1434, 3921, 1980, 7904, 6814, 2991, 7618, 8691, 6278, 5883, 10848, 8656, 5680, 6412, 3747, 1542, 3001, 8

In [ ]:
len(clusters['cluster 1']) # clusters

317

In [ ]:
for cl in cluster_data.get("children", []):
    print(len(cl.get("children", [])))

2167
1662
180

In [ ]:
df.head()

,City,Country,Description,Location,State,State_Abbrev,Longitude,Latitude,City_Longitude,City_Latitude,...,Apparition_Type,Time_of_Day,Total_Deaths,Percent_Under_21,Average_Mental_Health_Days,Average_Poor_Health_Days,Depression_Prevalence,Haunted_Place_Proximity,Distance_to_Nearest_Worship,Religion_Intersection
0,Ada,United States,Ada witch - Sometimes you can see a misty blue...,Ada Cemetery,Michigan,MI,-85.504893,42.962106,-85.495480,42.960727,...,Ghost,Evening,"4,548",2.60%,0.1480,0.2006,0.2134,False,9069.88,christian
1,Addison,United States,A little girl was killed suddenly while waitin...,North Adams Rd.,Michigan,MI,-84.381843,41.971425,-84.347168,41.986434,...,Unknown,Unknown,"4,548",2.60%,0.1352,0.1841,0.1961,True,4420.08,christian
2,Adrian,United States,If you take Gorman Rd. west towards Sand Creek...,Ghost Trestle,Michigan,MI,-84.035656,41.904538,-84.037166,41.897547,...,Spirit,Evening,"4,548",2.60%,0.1452,0.2058,0.1661,True,552.08,christian
3,Adrian,United States,"In the 1970's, one room, room 211, in the old ...",Siena Heights University,Michigan,MI,-84.017565,41.905712,-84.037166,41.897547,...,Unknown,Morning,"4,548",2.60%,0.1434,0.1902,0.1736,True,255.71,christian
4,Albion,United States,Kappa Delta Sorority - The Kappa Delta Sororit...,Albion College,Michigan,MI,-84.745177,42.244006,-84.753030,42.243097,...,Unknown,Unknown,"4,548",2.60%,0.1358,0.1829,0.1568,True,1686.25,christian

In [ ]:


["id", "Audio_Evidence", "Visual_Evidence", "Event_Type", "Aerodrome_Proximity", "Flight_HighTraffic", "Apparition_Type", "Time_of_day", "Religion_Intersection"]

['id',
 'Audio_Evidence',
 'Visual_Evidence',
 'Event_Type',
 'Aerodrome_Proximity',
 'Flight_HighTraffic',
 'Apparition_Type',
 'Time_of_day',
 'Religion_Intersection']

In [ ]:
column_order = [
    "Description", 'Location', 'City', 'State_Abbrev', 'Longitude', 'Latitude',
    'Haunted_Places_Date', 'Time_of_Day',
    # Required Features
    'Audio_Evidence', 'Visual_Evidence', 'Event_Type', 'Apparition_Type', 'Haunted_Places_Witness_Count', 'Haunted_Place_Proximity', 
    # Alcohol
    'Total_Deaths', 'Percent_Under_21', 
    #Airport
    'Aerodrome_Proximity', 'Aerodrome_Count', 'Flight_Intersection_Count', 'Flight_HighTraffic', 
    # Religion
    'Religion_Intersection', 'Distance_to_Nearest_Worship', 
    # Mental Health
    'Average_Poor_Health_Days', 'Depression_Prevalence', 'Average_Mental_Health_Days',
    # Jaccard
    'jaccard_score'
]

df_clust0 = pd.DataFrame.from_records(clusters["cluster 0"], index = "Haunted_Places_Id").drop(columns = ["id", "Country", "State", "City_Longitude", "City_Latitude"])[column_order]

df_clust1 = pd.DataFrame.from_records(clusters["cluster 1"], index = "Haunted_Places_Id").drop(columns = ["id", "Country", "State", "City_Longitude", "City_Latitude"])[column_order]

df_clust2 = pd.DataFrame.from_records(clusters["cluster 2"], index = "Haunted_Places_Id").drop(columns = ["id", "Country", "State", "City_Longitude", "City_Latitude"])[column_order]

In [ ]:
df_clust0.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2167 entries, 4925 to 10486
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Description                   2167 non-null   object
 1   Location                      2167 non-null   object
 2   City                          2167 non-null   object
 3   State_Abbrev                  2167 non-null   object
 4   Longitude                     2167 non-null   object
 5   Latitude                      2167 non-null   object
 6   Haunted_Places_Date           2167 non-null   object
 7   Time_of_Day                   2167 non-null   object
 8   Audio_Evidence                2167 non-null   object
 9   Visual_Evidence               2167 non-null   object
 10  Event_Type                    2167 non-null   object
 11  Apparition_Type               2167 non-null   object
 12  Haunted_Places_Witness_Count  2167 non-null   object
 13  Haunted_Place_Proximity       2167 non-null   object
 14  Total_Deaths                  2167 non-null   object
 15  Percent_Under_21              2167 non-null   object
 16  Aerodrome_Proximity           2167 non-null   object
 17  Aerodrome_Count               2167 non-null   object
 18  Flight_Intersection_Count     2167 non-null   object
 19  Flight_HighTraffic            2167 non-null   object
 20  Religion_Intersection         2167 non-null   object
 21  Distance_to_Nearest_Worship   2167 non-null   object
 22  Average_Poor_Health_Days      2167 non-null   object
 23  Depression_Prevalence         2167 non-null   object
 24  Average_Mental_Health_Days    2167 non-null   object
 25  jaccard_score                 2167 non-null   float64
dtypes: float64(1), object(25)
memory usage: 457.1+ KB

In [ ]:
df_clust1['Audio_Evidence'][0]

/var/folders/_b/bl5yw1q15msg5ky9z_04dpt40000gn/T/ipykernel_46893/2196577549.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_clust1['Audio_Evidence'][0]

'False'

In [ ]:
outfile = "../data/processed/haunted_places_features_added.tab"
columns = pd.read_csv(outfile, nrows = 0, sep = "\t").columns.tolist()
lst = ["Audio_Evidence", "Visual_Evidence"] 
any([(x in columns) for x in lst])

True

In [ ]:
clust2_idxs = df_clust2.index.tolist()
clust2_idxs = [int(i.strip()) for i in clust2_idxs]

df.loc[clust2_idxs]
print(len(df_clust2.index))

14005

## Structure of "circles.json"

- **Root (`children`)**
  - **Level 1 (`children`: list)**
    - **Level 2 (`children`: list of files)**
      - `{"name": "file.json  0.5", "size": "0.5"}`
      - `{"name": "another_file.json  0.5", "size": "0.5"}`